- name: variable preference
  hosts: local
  connection: local
  # vars:
  #   NAME: "Ansible from PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: please enter name
  #   private: false
  tasks:
  - name: printname
    # vars:
    #   NAME: "Ansible from Task"
    ansible.builtin.debug:
      msg: "Hi {{ NAME }}"