- name: demo on filters
  hosts: local
  connectin: local
  vars:
    topics: linux, shell, ansible, terraform
    tags:
      name: ansible
      project: roboshop
      component: catalogue
  tasks:
  - name: greeting
    ansible.biultin.debug:
      msg: "Hi Shankar, {{ GREETING | default('Good Morning') }}"

  - name: convert string to list
    ansible.builton.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"